apiVersion: v1
kind: Pod
metadata:
  name: minio{{rolename}}
  namespace: obj
  labels:
    # Label is used as selector in the service.
    app: minio
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: tls-ssl-minio
      items:
      - key: public.crt
        path: public.crt
      - key: private.key
        path: private.key
      - key: public.crt
        path: CAs/public.crt
  - name: data
    # This volume is based on PVC
    persistentVolumeClaim:
      # Name of the PVC created earlier
      claimName: node-pv-claim{{rolename}}
  containers:
  - name: minio
    # Pulls the default Minio image from Docker Hub
    image: minio/minio:latest
    args:
    - server
    - /storage/{{rolename}}/data
    env:
    # Minio access key and secret key
    #- name: MINIO_ACCESS_KEY
    #  value: "minio"
    #- name: MINIO_SECRET_KEY
    #  value: "minio123"
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_SECRET_KEY
    ports:
    - containerPort: 9000
      hostPort: {{MINIO_PORT}}
    # Mount the volume into the pod
    volumeMounts:
    - name: data # must match the volume name, above
      mountPath: "/storage/{{rolename}}/data"
    #- name: secret-volume
    #  mountPath: /root/.minio/certs
